#!/usr/bin/env node

import path from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const GENERATOR = '../src/generator/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

(async () => {
  await import(path.resolve(__dirname, GENERATOR));
})();
