#!/usr/bin/env node
/* eslint no-console: 0 */

const fs = require('fs/promises');
const path = require('path');

const subfont = require('subfont');
const webpack = require('webpack');

const { program } = require('commander');

const fetchData = require('../fetch-data');

global.window = {};
global.document = {};

// Args

program
  .name('build-site')
  .description('Compiles React app into static site.')
  .option('--analyze', 'Analyzes the build.');

program.parse();
const opts = program.opts();

(async () => {
  assertRequiredNode();
  const data = await runTask(fetchData(), 'Fetching data...');
  const files = await runTask(compileSite(data), 'Building site...');
  await runTask(optimizeFonts(files), 'Optimizing fonts...');

  console.info('');
  console.info('Finished! You can now serve these files with "yarn serve".');
  console.info('');
})();

function assertRequiredNode() {
  const major = process.version.split('.')[0].slice(1);
  if (major < 22) {
    throw new Error('This script must be run using node v22 or higher.');
  }
}

async function loadConfig(file) {
  let { default: module } = await import(file);
  if (typeof module === 'function') {
    module = await module();
  }
  return module;
}

async function compileSite(data) {
  const clientConfig = await loadConfig('../webpack.client.js');
  const generatorConfig = await loadConfig('../webpack.generator.js');

  if (opts.analyze) {
    const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');
    clientConfig.plugins.push(new BundleAnalyzerPlugin());
  }

  const compiler = webpack([clientConfig, generatorConfig]);

  await fs.rm(path.resolve('dist'), {
    force: true,
    recursive: true,
  });

  await runCompiler(compiler);

  const generator = require(path.resolve('dist/generator'));
  const template = await fs.readFile('dist/generator/template.html', 'utf-8');

  const files = await generator({
    data,
    template,
  });

  await fs.rm(path.resolve('dist/generator'), {
    force: true,
    recursive: true,
  });

  return files;
}

async function optimizeFonts(files) {
  await subfont({
    silent: true,
    inPlace: true,
    inlineCss: true,
    inputFiles: files,
    format: ['woff2'],
    output: 'dist',
  });
}

function runCompiler(compiler) {
  return new Promise((resolve, reject) => {
    compiler.run((err, stats) => {
      if (err) {
        reject(err);
      }
      if (Array.isArray(stats.stats)) {
        stats = stats.stats;
      } else {
        stats = [stats];
      }
      const errors = stats.flatMap((stat) => {
        return stat.compilation.errors;
      });

      if (errors.length) {
        reject(errors[0]);
      }

      resolve(stats);
    });
  });
}

async function runTask(promise, message) {
  if (process.stdout.isTTY) {
    return await withSpinner(promise, message);
  } else {
    return await withoutSpinner(promise, message);
  }
}

async function withSpinner(promise, message) {
  const { oraPromise } = await import('ora');

  return await oraPromise(promise, {
    prefixText: message,
    color: 'yellow',
    spinner: {
      interval: 80,
      frames: [
        '▰▱▱▱▱▱▱',
        '▰▰▱▱▱▱▱',
        '▰▰▰▱▱▱▱',
        '▰▰▰▰▱▱▱',
        '▰▰▰▰▰▱▱',
        '▰▰▰▰▰▰▱',
        '▰▰▰▰▰▰▰',
        '▰▱▱▱▱▱▱',
      ],
    },
  });
}

async function withoutSpinner(promise, message) {
  process.stdout.write(message);

  // Set a small timeout to allow non-TTY write
  // to flush as the webpack compiler has previously
  // hanged and we want to know which step we're on.
  await new Promise((resolve) => {
    setTimeout(resolve, 0);
  });

  const ret = await promise;
  process.stdout.write('done!\n');
  return ret;
}
