#!/usr/bin/env node

import { program } from 'commander';
import { createServer } from '../src/server/static.js';

program
  .name('serve-site')
  .description('Serves the static files from the output directory.');

program.parse();

createServer();
