#!/usr/bin/env node

const { program } = require('commander');

program
  .name('serve-site')
  .description('Serves the static files from the output directory.');

program.parse();

require('../serve/static');
