#!/usr/bin/env node

// Args

const { program } = require('commander');

program
  .name('start-site')
  .description('Starts the dev server and runs the app.');

program.parse();

require('../serve/dev');
