# Roles and role bindings to allow the default service
# account to patch deployments. This specifically allows
# a deployment of the static site via the API.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-deployer
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['patch']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-deployer
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: app-deployer
  apiGroup: rbac.authorization.k8s.io
